### ISSUE TITLE
Develop concrete proposal for the Student Showcase

### ISSUE THREAD

**Issue by ncoghlan** [ncoghlan/pycon-australia-education-seminar#2]
https://github.com/ncoghlan/pycon-australia-education-seminar/blob/master/2018/proposal.md#event-outline proposed that we run a Student Showcase in the Friday afternoon session at PyCon Australia 2018. To actually do that, we're going to need to come up with a concrete proposal to submit to the main conference organisers that covers:

- how we're going to manage submissions for this (since we'll presumably want to run it through schools rather than via direct applications by students)
- how we're going to manage the application process (since we'll presumably want to run it separately from the main CFP)
- how many slots we want to make available (the initial proposal was for 6 slots of 15 minutes each)
- whether a poster session style approach (with power and a table per student for demo laptops, phones, etc) might be a better option than presentation style
- if we go with presentation style, whether or not to record the presentations, whether or not to include moderated questions, and what guidelines to provide to students for presentation structure
- what the deadlines are going to be for all this (we already have one definite deadline, which is the regular CFP: we need to know whether we're going to be accepting 6 or 9 regular talks for the Education Seminar)

Relevant details:

- Location: [International Convention Centre](https://www.iccsydney.com.au/), Darling Harbour, Sydney
- Date: August 24th, 2018
- Time: ~4pm to ~6pm (based on 2017 schedule)

**Comment by ncoghlan** [comment]
@pyconau/education-seminar It occurs to me that a possible option for this year would be to use the afternoon session for a design workshop aimed at developing a concrete student showcase plan for 2019, rather than trying to actually run a separate Student Showcase this year (students would still be welcome to submit to the regular CFP, though).

Essentially, *we'd* spend the next 6 months coming up with a draft proposal (perhaps using some of the other student focused competitions at http://www.aussieeducator.org.au/resources/competitions.html for inspiration), but making sure we leave quite a few "Open questions for discussion" in that draft.

The aim in adopting that approach would be multi-purpose:

- actually get feedback on the idea from any teachers and students that stick around for the design workshop
- start promotion of the idea this year, and build a (mailing!) list of teachers that have expressed a potential interest in having their students make submissions to a showcase, as well as a list of teachers that may be interested in participating in a selection panel
- maybe start building a more explicitly participatory community around the Education Seminar (rather than having the mailing list be purely a broadcast list from the organisers to folks that have signed up)

We'd essentially need to "pre-apply" for 2019's Specialist Day so we can do the associated forward planning (we could even suggest that as a general refinement for the specialist track selection process: for the first year in each new city, give specialist track organisers the opportunity to apply for the second year in advance if they have a compelling justification for why they need to do so)

**Comment by ncoghlan** [comment]
@nickyringland You've indicated you're still keen to run an actual showcase this year rather than just a planning session for a 2019 showcase.

Could you work backwards from the August 24th seminar date and figure out what that would mean in terms of reasonable deadlines for:

- sending out acceptance notices to students (so they and their teachers/guardians can organise any required travel)
- receiving submissions from teachers for students they'd like to see present at the showcase (with time to review them for inclusion)
- receiving commitments from teachers that they will be running student projects for year 11/12 students that may form a suitable basis for nominations
- the potential additional budget needed to make it so that acceptance isn't a financial burden for selected students

If you're confident we can make it work, I believe you, but we also need to be able to convince the main conference organisers of that before we start asking for special free ticketing arrangements to allow parents & friends to attend solely for the post-afternoon-session on the Friday.

**Comment by nickyringland** [comment]
I'll have a chat this week with Amanda and Bruce for a teachers' perspective of timelines and report back.

**Comment by nickyringland** [comment]
@hogesonline @bruce1979 and I have had a chat, and we all agree that this is very possible. (And that it'll be fantastic!)

Timeline:
- Announce that this will be happening ASAP.
- Call for papers opens early May - when school goes back in Term 2. (School holidays end at end of April).
- Submissions close early June.
- Students announced mid June.
- (Two months for schools to organise travel etc.)
- Awesome presentations and posters!

This allows us to be flexible with the number of presentations / posters we accept, and gives plenty of time for as many students to submit proposals as possible.

**Comment by ncoghlan** [comment]
Cool :)

Given that, I'll ask the main conf organisers if we can proceed on the assumption that the final session on Friday will either be an open house, or else that we'll be able to give out free "Student Showcase only" tickets to students' friends & family.

**Comment by ncoghlan** [comment]
I finally sent the relevant questions to the main conf organisers list, so we'll see what they have to say. I suspect we'll need to organise a video conference in order to figure out the details (or at least enough of them to start planning with confidence).

**Comment by ncoghlan** [comment]
@nickyringland and I met up with @glasnt  on March 22nd, and we're going ahead using the timeline Nicky gave above.

Follow-up issues:

* https://github.com/pyconau/pycon-australia-education-seminar/issues/5 (Provide ACA contact info for Working with Children checks)
* https://github.com/pyconau/pycon-australia-education-seminar/issues/6 (Providing Edu Seminar specific text for the PyCon AU website and CFP announcement)
* https://github.com/pyconau/pycon-australia-education-seminar/issues/4 (Existing issue about getting Code Club as a community partner again, I'll just tack asking for their help promoting the Student Showcase to high schools on to that discussion)
* https://github.com/pyconau/pycon-australia-education-seminar/issues/7 (Getting contact information together so we can reach out to past speakers regarding the 2018 Education Seminar in general, and the Student Showcase in particular)

**Comment by ncoghlan** [comment]
Heh, I broke out the follow-up issues yesterday, but missed the step of marking this one as done! :)
