### ISSUE TITLE
Prepare Education Seminar website & CFP text

### ISSUE THREAD

**Issue by ncoghlan** [ncoghlan/pycon-australia-education-seminar#6]
The site text that we had for 2017 can be found here: https://2017.pycon-au.org/program/education-seminar/

We can likely re-use a lot of that, but we're going to need new text for the Student Showcase.

@nickyringland, would you be OK with tackling this? You have a clearer idea than I do regarding how you want to frame the Student Showcase, and I think that's the main *new* work involved this year (vs what we can just bring forward from last year).

**Comment by nickyringland** [comment]
@hogesonline and I have it in our diary to tackle this tomorrow after having made a start on it this weekend.

**Comment by ncoghlan** [comment]
Something I just noticed in writing to Code Club Australia for #4 is that it appears I forgot to add the event sponsor and community partner info to the 2017 page. I also forgot to update it appropriately after the schedule was announced, and registration opened.

That means https://2016.pycon-au.org/programme/python_in_education_seminar is a better guide for mentioning community partners appropriately.

**Comment by ncoghlan** [comment]
Inferring some extra info from the draft papercall.io CFP page :)

* Student showcase write-up: https://docs.google.com/document/d/1-nwgL9ijIFImQQXaEluEkhDeU1vvP61aXA7e98z0v5s/edit?usp=sharing
* Application form: https://docs.google.com/forms/d/e/1FAIpQLSeT8witEHPrvvYLr4QflguAYVr3zdvHKNdDnoFm2qR_HHDhBg/viewform
* Short URL for the form: http://bit.ly/pyconau-2018-student-showcase 

The current drafts use the phrase "Student Track" in a few places - it would be nice to stick with "Student Showcase" throughout.

**Comment by ncoghlan** [comment]
Also see https://github.com/glasnt/2018.pycon-au.org/issues/14

**Comment by ncoghlan** [comment]
From Katie's reply at https://github.com/glasnt/2018.pycon-au.org/issues/14#issuecomment-383419881, we can add the "Student Showcase submission guide" to the main site as "speak/showcase".

For anything that's the same as the main CFP, we should be able to just link back to that, rather than repeating the same material.

**Comment by ncoghlan** [comment]
@nickyringland Reviewing the Student Showcase application form, it doesn't have a field for the video recording consent notice. Perhaps we should just skip recording the showcase so we don't need to worry about managing the related logistics of getting consent for that from parents/guardians?

**Comment by ncoghlan** [comment]
Initial draft PR for the main site submitted here: https://github.com/glasnt/2018.pycon-au.org/pull/25

I also invited you both as collaborators on https://github.com/ncoghlan/2018.pycon-au.org/, since I won't be around to edit it until after work tomorrow evening.

Once the PR's merged, the stable link should be to https://2018.pycon-au.org/speak/showcase

**Comment by nickyringland** [comment]
I think video recording shouldn't be too much of a hurdle, but figured we could sort it out after proposals were accepted. Having a talk up is a very cool part of Pycon, and something I think a lot of the students would be very excited about. 
So long as it's not a dealbreaker if some of the students ask to not be put online, even if that means it takes longer for the videos to go up, or if I need to volunteer some of my time to help the audio folks, I think I'd still like to be able to give students who have been accepted the offer. ACA can hold on to video consent for minors forms etc, - we've got similar ones for NCSS/GPN that we can draw from.

**Comment by ncoghlan** [comment]
That makes sense - filed https://github.com/pyconau/pycon-australia-education-seminar/issues/8 to cover following up with the AV team about it :)

**Comment by ncoghlan** [comment]
This was finished a while back, I noticed it was still open while filing #9.
